checksumBehavior: update

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

pnpMode: loose

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false
