name: "Release"
description: "Calculates a new version number based on PR labels."

inputs:
  github-token:
    description: "GitHub token to use within the action when it is performing writing. Defaults to the GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}

outputs:
  should-publish:
    description: "Whether or not a publish should be done"
  version:
    description: " Version number to publish with"

runs:
  using: "node12"
  main: "dist/index.js"
